### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by Allesanddro** [hell-sh/dstatnode#3]
Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/opt/dstat/dstatnode.jar) to constructor java.nio.DirectByteBuffer(long,int)

**Comment by timmyrs** [comment]
What system? What java version?

**Comment by Allesanddro** [comment]
running Ubuntu 18.04 via default-jre so should be 10 not sure need to Check
tomorrow

timmyrs <notifications@github.com> schrieb am So., 28. Okt. 2018, 12:56
vorm.:

**Comment by timmyrs** [comment]
![image](https://user-images.githubusercontent.com/11009697/47613733-bd417a00-da94-11e8-9639-9c350d4e07b9.png)
Works for me on Ubuntu 18.04 with Java 10.0.2. What you're seeing is just a warning.
